---
- name:
  hosts: localhost
  tasks:
    - name:
      yum:
        name: httpd
        state: latest
    - name:
      service:
        name: httpd
        enabled: true
        state: started
    - name:  
      file:
        path: /var/www/html/index.html
        state: touch
        mode: 0644
    - name:
      lineinfile:
        path: /var/www/html/index.html
        line: "hello class"
        state: present
    - name:
      service:
        name: httpd
        state: restarted
...        
